[tools]
"vfox-pulumi:pulumiverse/pulumi-time" = "latest"
"vfox-pulumi:pulumi/pulumi-std" = "latest"
"vfox-pulumi:pulumi/pulumi-azure" = "latest"
"vfox-pulumi:pulumi/pulumi-random" = "latest"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "latest"
